### ISSUE TITLE
[Bug] ShineFx in-game doesnt match editor

### ISSUE THREAD

**Issue by nonunknown** [arkology/ShaderV#5]
https://user-images.githubusercontent.com/58845030/106129212-cd96a280-613e-11eb-9977-f8f32b2bc5bf.mp4

Ive change the shine speed with sintime and saved the shader,but when game opens, it doesnt match. (made the same steps with sphereUV and worked well) 

![image](https://user-images.githubusercontent.com/58845030/106130351-fff4cf80-613f-11eb-8c68-ff9b3bee20eb.png)

**Comment by arkology** [comment]
@nonunknown if i understand this video correctly, sinTIME speed and amplitude in editor and in game are different, right?
If so, this is Godot bug with default visual nodes values (default values work in editor, but not in running project). I made default values to almost all nodes for better usability, but, unfortunately, it can't be used because of bug in Godot itself. Not sure if anyone reported this bug in godot repo.
But there's workaround. Set to ports with default values scalar or uniform nodes, and it will work correctly.

**Comment by nonunknown** [comment]
thanks for your response, well in my case Physics fps is 15, and Process fps is 60, but I think this doesnt matter because the bug still happens

**Comment by arkology** [comment]
Still don't understand what exactly means "doesn't match" :)
If you question is about different update speed in your video, unfocused Godot editor window has reduced fps since 3.2.x

**Comment by nonunknown** [comment]
as you can see in godot is pretty fast, its not reduced, and in-game is veryslow (the shihe fx)

**Comment by arkology** [comment]
Did you tried to set scalar nodes to sinTIME input ports, as I advised earlier?
Theoretically, there should be absolutely no difference between in-game and editor views related to plugin, because it is still the same shader. The only difference, Godot ignores build-in shader nodes values in-game. When you set 10/2 as values of sinTIME, it will be 10/2 in editor and default 1/1 in running project. As I already said, this is Godot bug.

**Comment by nonunknown** [comment]
ok I'll try and give you aa feedback

**Comment by nonunknown** [comment]
![image](https://user-images.githubusercontent.com/58845030/106273818-081d3f80-6212-11eb-821f-6ff1670f6b20.png)
WORKED! Ty.

**Comment by arkology** [comment]
@nonunknown happy to help! Now closing.
